name: 'Pandoc Conversion and Pages Deployment'
description: 'Converts a markdown file to HTML and deploys to GitHub Pages'
inputs:
  gh_token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check if markdown or template file was pushed
      id: check_file
      shell: bash
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q -e "assets/index.md" -e "assets/template.html"; then
          echo "files_changed=true" >> $GITHUB_ENV
        else
          echo "files_changed=false" >> $GITHUB_ENV
        fi  
    - name: Setup Pandoc
      if: env.files_changed == 'true'
      shell: bash
      run: sudo apt-get install -y pandoc
    - name: Convert markdown to HTML
      if: env.files_changed == 'true'
      shell: bash
      run: |
        pandoc --standalone --template "assets/template.html" "assets/index.md" -o "public/index.html"
        git config --global user.email "github-action@github.com"
        git config --global user.name "GitHub Action"
        git add "public/index.html"
        git commit -m "update index.html"
        git push
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        if: github.ref == 'refs/heads/main'
        github_token: ${{ inputs.gh_token }}
        publish_dir: public
